### ISSUE TITLE
signaling server not working

### ISSUE THREAD

**Issue by jonasrhee1208wastaken** [cloudlink-omega/cl5#1]
its on penguinmod, on a chromebook, and it is just not connecting

**Comment by MikeDev101** [comment]
Can you provide me with details regarding your issue? Can you also double-check for me that you're connecting to a valid server with https://github.com/cloudlink-omega/extension ?

**Comment by jonasrhee1208wastaken** [comment]
ok. the UGI is 23e5c25e-0bed-11ef-8a43-325096b39f47
the signaling server URL is wss://omega.mikedev101.cc/api/v0/signaling?ugi=23e5c25e-0bed-11ef-8a43-325096b39f47%2Fapi%2Fv0%2Fsignaling&ugi=23e5c25e-0bed-11ef-8a43-325096b39f47

**Comment by jonasrhee1208wastaken** [comment]
ohhhhhh i dont change the UGI?

**Comment by MikeDev101** [comment]
Unless if you have a valid registered game with Omega, use the default one provided by the extension. Closing as invalid.

**Comment by jonasrhee1208wastaken** [comment]
or how do i get a UGI

**Comment by jonasrhee1208wastaken** [comment]
oh

**Comment by MikeDev101** [comment]
It is a manual process at the moment, but all registration requests are handled in our Discord server: https://discord.gg/BZ7TWeMF75

**Comment by jonasrhee1208wastaken** [comment]
still not working

**Comment by josephlombardo1** [comment]
did you get a email? MikeDEV101 did a update and now needs email verification.
