### ISSUE TITLE
Signaling server disconnecting at token auth

### ISSUE THREAD

**Issue by josephlombardo1** [cloudlink-omega/cl5#3]
Every time I go to use the session token from cloudlink omega to authenticate, it disconnects from the server.
My code is this:

`Cloudlink Omega: Use [https://omega.mikedev101.cc] as API server`
`Cloudlink Omega: Use [wss://omega.mikedev101.cc] as Signaling server`
`Cloudlink 5: Connect to signaling server [Cloudlink Omega: Signaling Server URL with set UGI]`
`Cloudlink Omega: Login with Email [email] Password [password]`
It disconnects when this line of code is executed:
`Cloudlink 5: Authenticate with token [Cloudlink Omega: Session Token]`

Can someone please help me?
BTW i am using the default ugi

**Comment by MikeDev101** [comment]
Hey there, the only time this would occur is if you haven't verified your email address. As a security measure I recently began email verification enforcement. Make sure to check your spam inbox for a message from `cloudlinkomega@gmail.com`.

**Comment by josephlombardo1** [comment]
I just verified. Thanks for the help.
